### ISSUE TITLE
WASM

### ISSUE THREAD

**Issue by jcampbell05** [tbodt/ish#102]
Maybe we should use WASM for the assembly to make it portable.

**Comment by tbodt** [comment]
I've thought about this for a while and there are some big problems with it, such as:

 - WASM is not designed for this sort of jit, and thus has no way of modifying code once you've compiled it without totally recompiling it.
 - How do you implement shared file mappings?
 - System calls would take on the order of 500 microseconds since all communication between WebKit and the app needs to go over XPC.
