### ISSUE TITLE
SQLite in Python2 fails with disk I/O error

### ISSUE THREAD

**Issue by jmoutte** [tbodt/ish#217]
I am trying to install and use the Google Cloud SDK on iSH. Initialisation fails due to Python being unable to use SQLite to manage the credentials database.

See test below:
```
Juliens-iPad:~/google-cloud-sdk$ python                                                    
Python 2.7.15 (default, Aug 16 2018, 14:17:07)                                             
[GCC 6.4.0] on linux2                                                                      
Type "help", "copyright", "credits" or "license" for more information.                     
>>> import sqlite3                                                                         
>>> db = sqlite.connect('toto.db')                                                         
Traceback (most recent call last):                                                         
  File "<stdin>", line 1, in <module>                                                      
NameError: name 'sqlite' is not defined                                                    
>>> db = sqlite3.connect('toto.db')                                                        
>>> cursor = db.cursor()                                                                   
>>> cursor.execute('''CREATE TABLE users(id INTEGER PRIMARY KEY, name TEXT)''')            
Traceback (most recent call last):                                                         
  File "<stdin>", line 1, in <module>                                                      
sqlite3.OperationalError: disk I/O error                                                   
>>>
```

The actual error from SQLite is SQLITE_IOERR_LOCK (3850)

**Comment by tbodt** [comment]
POSIX file locks aren't working because they're per-process which means hell.

**Comment by jmoutte** [comment]
thanks for the feedback! Is that a NOT_GONNA_HAPPEN or MAYBE_LATER ? :)

Also you might want to share a bit more details if someone wants to try to implement it..

**Comment by tbodt** [comment]
It's more of a SOMEONE_PLEASE_DO_THIS_FOR_ME. Here's the deal:

There are two different file locking mechanisms supported on Linux, flock() and fcntl(). Handling flock() is easy: just call the iOS implementation of flock(). This works fine because flock() locks are owned by a file descriptor.

fcntl() locks, on the other hand, are owned by the entire process, and on iOS you only have one process. So if one emulated process called fcntl() to acquire a lock, this lock is now also owned by every other emulated process, which is definitely not how it's supposed to work.

The only solution I can think of is managing fcntl() locks manually in a file lock structure, using condition variables for waits. The question though is, what is the file lock structure associated with? On Linux it's owned by the `struct inode`, and there's no equivalent of that in iSH. The best you can do is obtain inode numbers. So you'd need a hashtable for each mount mapping inode numbers to file lock data, and then you need to worry about what happens when a file is deleted and its inode number gets reused, etc. This all is a bit beyond my complexity threshold for one sitting, so I keep putting it off and hoping someone else will implement it.

**Comment by jmoutte** [comment]
Looks like the rest is working fine. I implemented a mock of fcntl locking and could insert data in sqlite.
![fcntl_sqlite](https://user-images.githubusercontent.com/655311/50513592-f4360b00-0a98-11e9-8897-28b37db1c8bb.png)

**Comment by tbodt** [comment]
The problem with that fcntl locking implementation is if there are two sqlite processes running on the same database, the database will very quickly go corrupt.

**Comment by tbodt** [comment]
If you open a file twice and lock the first FD with flock, then trying to lock the second one will block, because the lock is currently held by the first FD. If you use fcntl, you can lock both FDs at the same time, because the lock is held by the whole process, not the FD.

**Comment by trwyant** [comment]
This is also an issue in C. Oddly enough, it usually worked for me in Perl under builds 40 and 42 (using DBD::SQLite). But under 44 Perl is now consistent with everyone else. I have tried extended status, but not gotten anything more illuminating.

**Comment by tbodt** [comment]
This has been fixed for about a month now
