### ISSUE TITLE
There's no way this is getting on the App Store

### ISSUE THREAD

**Issue by Ronsor** [tbodt/ish#34]
Apple isn't going to let you download executable code from the internet (it's technically not allowed).

**Comment by tbodt** [comment]
¯\_(ツ)_/¯

**Comment by kasik96** [comment]
@Ronsor @tbodt  You are wrong. Apple allowed Executable code back in iOS 11 for educational purposes and developer tools. So theoretically it should be allowed. 
Whole statement:

> 2.5.2 Apps should be self-contained in their bundles, and may not read or write data outside the designated container area, nor may they download, install, or execute code which introduces or changes features or functionality of the app, including other apps. Educational apps designed to teach, develop, or allow students to test executable code may, in limited circumstances, download code provided that such code is not used for other purposes. Such apps must make the source code provided by the Application completely viewable and editable by the user.

You can read more about it here: https://developer.apple.com/app-store/review/guidelines/#software-requirements

**Comment by tbodt** [comment]
The part I'm not sure about is
> Such apps must make the source code provided by the Application completely viewable and editable by the user.

I could argue that all the software available on the Alpine repo is open source, and you could download the code and build the software from source if you wanted to make changes.

**Comment by kasik96** [comment]
In App Store there is Power DOS and iDOS 2 which works similar way. So i think it pretty good chance 😊.

**Comment by mirorauhala** [comment]
Well if not for the ”Executable Code”, it cannot be published to the App Store due to being licensed as GPLv3. Apple uses heavy DRM and signature checking on iOS apps to detect modified code from running, prevention-of-which is one of the goals of GPLv3. 

From the [license](https://github.com/tbodt/ish/blob/d058149e5d12812a5b78c4533fee550220dd2283/LICENSE#L179):
>   3. Protecting Users' Legal Rights From Anti-Circumvention Law.
> 
>   No covered work shall be deemed part of an effective technological
> measure under any applicable law fulfilling obligations under article
> 11 of the WIPO copyright treaty adopted on 20 December 1996, or
> similar laws prohibiting or restricting circumvention of such
> measures.
> 
>   When you convey a covered work, you waive any legal power to forbid
> circumvention of technological measures to the extent such circumvention
> is effected by exercising rights under this License with respect to
> the covered work, and you disclaim any intention to limit operation or
> modification of the work as a means of enforcing, against the work's
> users, your or third parties' legal rights to forbid circumvention of
> technological measures.

More to read from:
https://en.wikipedia.org/wiki/Tivoization

**Comment by tbodt** [comment]
I'm using an additional condition on the GPL to allow app store distribution: https://github.com/tbodt/ish/blob/master/LICENSE.IOS

**Comment by mirorauhala** [comment]
Aha. I missed that.

**Comment by mirorauhala** [comment]
However, this struck my eye:

> In other words, as long as you comply with the GPL in all other respects,
> including its requirements to provide users with source code and the
> text of the license, we will not object to your distribution of the
> iSH app through the App Store.

Does Apple deliver the source through appstore?

**Comment by tbodt** [comment]
No, but the GPL doesn't require the binaries and source to come from the same place. As long as the source corresponding to each binary is publicly available somewhere, that's fine.

**Comment by mirorauhala** [comment]
Yes, it also doesn’t say that it has to be on the internet. ”Any medium” so DVDs or thousands of pages paper.

**Comment by tbodt** [comment]
It must be machine readable. Any form where I can turn it into files that I can build and upload to github is fine with me.

**Comment by mirorauhala** [comment]
Hmm... so the ”illegal copy app” was illegal because there wasn’t any source available, anywhere. However, isn’t that then a violation of my rights. Yes it sounds silly but bear with me :D

I download a GPLv3 licensed app which grants me verbatim copy of the source and anti-DRM clause. Now we know the App Store uses DRM. The twist is that you said ”As long as the source corresponding to each binary is publicly available somewhere, that's fine by me.”

Now that’s fine by you, but licenses are two-party deals. I use your software under the terms you give and grant. But I could still demand that the source come from the App Store if I was not fine with it.

Maybe i should become a litigator haha 😸

**Comment by mirorauhala** [comment]
But to be real though. What I’m trying to say is that it may just be easier for Apple to not allow your app to enter the App Store as long as it is licensed under GPLv3. Regardless of any excemptions you’ve made.

Easier is just easier. Maybe safer (for them) in this case.

**Comment by tbodt** [comment]
> But I could still demand that the source come from the App Store if I was not fine with it.

I don't understand why this would be the case.

mosh is licensed under GPLv3 with this same additional condition and there are a number of apps on the store that use it. The Blink app also does this. It should be fine.

**Comment by mirorauhala** [comment]
Interesting... well in that case you may be right :D
