### ISSUE TITLE
Long term goals

### ISSUE THREAD

**Issue by brandonros** [tbodt/ish#36]
This might be a pipe dream and a whole lot of stupidity/misinformation so I apologize ahead of time but... could you not have just have cross-compiled QEMU's x86 software emulation to the ARM instructions iOS devices use? Would that approach even be possible/let alone offer you any benefit?

Do you see this as the basis for a "VirtualBox" for iOS? Emulating an ethernet controller, graphics controller, etc...

If people could use a Bluetooth mouse + keyboard with their iPad through an x86-backed virtual machine to develop... that might be something? Obviously performance would be a concern...

**Comment by tbodt** [comment]
If I could have compiled QEMU to iOS this project would have been a lot easier. The iOS sandbox doesn't allow you to have memory that's both writable and executable, which QEMU heavily relies on.

I don't see a need for emulating an ethernet controller, since iOS already has network support. Emulating the framebuffer and input devices could allow X11 to run, which would be hella trippy but not necessarily useful (mostly because of performance.)

**Comment by brandonros** [comment]
Do you think this will ever get to the point of X11 support?

**Comment by tbodt** [comment]
We'll see...

**Comment by brandonros** [comment]
> The iOS sandbox doesn't allow you to have memory that's both writable and executable, which QEMU heavily relies on.

Is that true for a rooted device too? As an app maybe, but... do background daemons get different security exceptions? :)

**Comment by tbodt** [comment]
That limitation doesn't apply to jailbroken devices, but if you have a jailbroken device you already have access to a full Unix environment without needing any emulation.

**Comment by brandonros** [comment]
Are you aware of any mouse support on jailbroken devices?

**Comment by tbodt** [comment]
No
