### ISSUE TITLE
Wrong answer for 8.96/22.4

### ISSUE THREAD

**Issue by tbodt** [tbodt/ish#581]
It should be 0.4, but a user reported that in Python it gives 0.400...001.

**Comment by MasonProtter** [comment]
That's just floating point arithmetic. Nothing to do with Ish. See also
```
>>> 0.2 + 0.1
0.30000000000000004
```

**Comment by tbodt** [comment]
Never mind then. Spotlight gets it right, somehow.

**Comment by MasonProtter** [comment]
Same with a standard pocket calculator. They're doing decimal arithmetic instead of floating point.

**Comment by MasonProtter** [comment]
Turns out Spotlight is just rounding at the display stage.

Compare
![Screen Shot 2019-12-13 at 7 59 36 PM](https://user-images.githubusercontent.com/29157027/70842619-4162d800-1de3-11ea-838b-590adbc70a85.png)
and
![Screen Shot 2019-12-13 at 7 59 32 PM](https://user-images.githubusercontent.com/29157027/70842622-4758b900-1de3-11ea-9b91-8925ee4aa598.png)
